# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2019-09-14 18:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190914_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 34, 38, 246680, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 14, 18, 34, 38, 247000, tzinfo=utc)),
        ),
    ]
